// Generated by ./scripts/gensrc.sh
source "docker" "php-8-1-20-04" {
  image = "${var.source_repository}:20.04"
  commit = true
  pull = false
  changes = [
    "ENTRYPOINT [\"${local.image_entrypoint}\"]",
    "CMD [\"${join("\", \"", local.image_default_command)}\"]",
    "WORKDIR /",
    "LABEL org.opencontainers.image.title=\"PHP 8.1 (Ubuntu 20.04)\"",
    "LABEL org.opencontainers.image.description=\"PHP image based on ubuntu.\"",
    "LABEL org.opencontainers.image.base.name=${var.repository}:8.1-20.04",
    "LABEL org.opencontainers.image.authors=\"${join(", ", local.authors)}\"",
    "LABEL org.opencontainers.image.created=${timestamp()}",
    "LABEL org.opencontainers.image.version=8.1-20.04",
    "LABEL org.opencontainers.image.source=\"${local.source}\""
  ]
}
source "docker" "php-8-1-22-04" {
  image = "${var.source_repository}:22.04"
  commit = true
  pull = false
  changes = [
    "ENTRYPOINT [\"${local.image_entrypoint}\"]",
    "CMD [\"${join("\", \"", local.image_default_command)}\"]",
    "WORKDIR /",
    "LABEL org.opencontainers.image.title=\"PHP 8.1 (Ubuntu 22.04)\"",
    "LABEL org.opencontainers.image.description=\"PHP image based on ubuntu.\"",
    "LABEL org.opencontainers.image.base.name=${var.repository}:8.1-22.04",
    "LABEL org.opencontainers.image.authors=\"${join(", ", local.authors)}\"",
    "LABEL org.opencontainers.image.created=${timestamp()}",
    "LABEL org.opencontainers.image.version=8.1-22.04",
    "LABEL org.opencontainers.image.source=\"${local.source}\""
  ]
}
source "docker" "php-8-2-20-04" {
  image = "${var.source_repository}:20.04"
  commit = true
  pull = false
  changes = [
    "ENTRYPOINT [\"${local.image_entrypoint}\"]",
    "CMD [\"${join("\", \"", local.image_default_command)}\"]",
    "WORKDIR /",
    "LABEL org.opencontainers.image.title=\"PHP 8.2 (Ubuntu 20.04)\"",
    "LABEL org.opencontainers.image.description=\"PHP image based on ubuntu.\"",
    "LABEL org.opencontainers.image.base.name=${var.repository}:8.2-20.04",
    "LABEL org.opencontainers.image.authors=\"${join(", ", local.authors)}\"",
    "LABEL org.opencontainers.image.created=${timestamp()}",
    "LABEL org.opencontainers.image.version=8.2-20.04",
    "LABEL org.opencontainers.image.source=\"${local.source}\""
  ]
}
source "docker" "php-8-2-22-04" {
  image = "${var.source_repository}:22.04"
  commit = true
  pull = false
  changes = [
    "ENTRYPOINT [\"${local.image_entrypoint}\"]",
    "CMD [\"${join("\", \"", local.image_default_command)}\"]",
    "WORKDIR /",
    "LABEL org.opencontainers.image.title=\"PHP 8.2 (Ubuntu 22.04)\"",
    "LABEL org.opencontainers.image.description=\"PHP image based on ubuntu.\"",
    "LABEL org.opencontainers.image.base.name=${var.repository}:8.2-22.04",
    "LABEL org.opencontainers.image.authors=\"${join(", ", local.authors)}\"",
    "LABEL org.opencontainers.image.created=${timestamp()}",
    "LABEL org.opencontainers.image.version=8.2-22.04",
    "LABEL org.opencontainers.image.source=\"${local.source}\""
  ]
}
source "docker" "php-8-3-20-04" {
  image = "${var.source_repository}:20.04"
  commit = true
  pull = false
  changes = [
    "ENTRYPOINT [\"${local.image_entrypoint}\"]",
    "CMD [\"${join("\", \"", local.image_default_command)}\"]",
    "WORKDIR /",
    "LABEL org.opencontainers.image.title=\"PHP 8.3 (Ubuntu 20.04)\"",
    "LABEL org.opencontainers.image.description=\"PHP image based on ubuntu.\"",
    "LABEL org.opencontainers.image.base.name=${var.repository}:8.3-20.04",
    "LABEL org.opencontainers.image.authors=\"${join(", ", local.authors)}\"",
    "LABEL org.opencontainers.image.created=${timestamp()}",
    "LABEL org.opencontainers.image.version=8.3-20.04",
    "LABEL org.opencontainers.image.source=\"${local.source}\""
  ]
}
source "docker" "php-8-3-22-04" {
  image = "${var.source_repository}:22.04"
  commit = true
  pull = false
  changes = [
    "ENTRYPOINT [\"${local.image_entrypoint}\"]",
    "CMD [\"${join("\", \"", local.image_default_command)}\"]",
    "WORKDIR /",
    "LABEL org.opencontainers.image.title=\"PHP 8.3 (Ubuntu 22.04)\"",
    "LABEL org.opencontainers.image.description=\"PHP image based on ubuntu.\"",
    "LABEL org.opencontainers.image.base.name=${var.repository}:8.3-22.04",
    "LABEL org.opencontainers.image.authors=\"${join(", ", local.authors)}\"",
    "LABEL org.opencontainers.image.created=${timestamp()}",
    "LABEL org.opencontainers.image.version=8.3-22.04",
    "LABEL org.opencontainers.image.source=\"${local.source}\""
  ]
}
